before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install 
language: node_js
node_js:
  - '0.10'
notifications:
  email:
    - cristian.roselli@stamplay.com
    - claudio.petrini@stamplay.com
  